apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      name: apache
    spec:
      containers:
        - name: apache
          image: 787379092555.dkr.ecr.us-east-1.amazonaws.com/ecomapp-aws-k8s
          envFrom:
            - configMapRef:
                name: ecom
          env:
            #- name: DB_USER
            # value: "wronguser"
            - name: FEATURE_DARK_MODE
              value: "true"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecom
                  key: DB_USER

      imagePullSecrets:
        - name: dockcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      name: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb

          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: my-script-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: my-script-volume
          configMap:
            name: my-script-configmap
            defaultMode: 0744

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: mysql
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: apache-service
  namespace: default
spec:
  ports:
    - nodePort: 30941
      port: 30000
      protocol: TCP
      targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
