apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJqaW1teXVscmljaCIsInBhc3N3b3JkIjoiZG9ja2VyamltbXk5OS4iLCJlbWFpbCI6ImppbW15dWxyaWNoNDhAZ21haWwuY29tIiwiYXV0aCI6ImFtbHRiWGwxYkhKcFkyZzZaRzlqYTJWeWFtbHRiWGs1T1M0PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2024-05-24T21:05:42Z"
  name: dockcred
  namespace: default
  resourceVersion: "4576"
  uid: a08a8b72-2bdc-47bf-9756-75efacc6311d
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-script-configmap
data:
  my-script.sql: |
    #!/bin/bash
    CREATE DATABASE ecomdb;
    CREATE USER 'ecomuser'@'localhost' IDENTIFIED BY 'Ecompasswd99.';
    GRANT ALL PRIVILEGES ON *.* TO 'ecomuser'@'localhost';
    CREATE USER 'ecomuser'@'%' IDENTIFIED BY 'Ecompasswd99.';
    GRANT ALL PRIVILEGES ON *.* TO 'ecomuser'@'%';

    FLUSH PRIVILEGES;

    USE ecomdb;
    CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;

    INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
      name: apache
    spec:
      containers:
        - name: apache
          image: 787379092555.dkr.ecr.us-east-1.amazonaws.com/ecomapp-aws-k8s
          env:
            #- name: DB_USER
            # value: "wronguser"
            - name: FEATURE_DARK_MODE
              value: "true"
            - name: DB_HOST
              value: "mysql"

      imagePullSecrets:
        - name: dockcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      name: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb

          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: my-script-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: my-script-volume
          configMap:
            name: my-script-configmap
            defaultMode: 0744

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: apache-service
  namespace: default
spec:
  ports:
    - nodePort: 30941
      port: 30000
      protocol: TCP
      targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
