apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: apache
spec:
  containers:
    - name: apache
      image: 787379092555.dkr.ecr.us-east-1.amazonaws.com/ecomapp-aws-k8s
      env:
        - name: FEATURE_DARK_MODE
          value: "true"
        - name: DB_USER
          value: ""
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_HOST
          value: ""

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mariadb
  imagePullSecrets:
    - name: dockcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: apache-service
  namespace: default

spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
