apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: db
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: mariadb
      labels:
        app: db
    spec:
      volumes:
        {{- .Files.Get "volume-conf.yaml" | nindent 8 }}
      containers:
        - name: mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: db
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: probe
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
          envFrom:
            - configMapRef:
                name: ecom
          env:
            {{- range $key, $val := .Values.env }}
              - name: {{ $val.name }}
                value: {{ $val.value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
