apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    app: db
