apiVersion: v1
kind: Service
metadata:
  name: apache-service   
  labels:
    app: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30941
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web
