            - name: Deploy Helm chart to AWS EKS Cluster
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-deploy-eks-helm@016d790e0f780d468a99a4ded0d10636d94daad5
  uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
  with:
    # AWS credentials used to login to eks.
    aws-secret-access-key: # optional
    # AWS credentials used to login to eks.
    aws-access-key-id: # optional
    # AWS region to use (default: us-west-2)
    aws-region: # default is us-west-2
    # EKS cluster name.
    cluster-name: 
    # EKS cluster admin role arn.
    cluster-role-arn: # optional
    # Comma separated list of helm values files.
    config-files: # optional
    # Kubernetes namespace to use.
    namespace: # optional
    # Comma separated list of value sets for helms. e.x: key1=value1,key2=value2
    values: # optional
    # Name of the helm deploy.
    name: 
    # Specify whether you want to install or uninstall the target helm chart
    action: # optional, default is install
    # Toggles dry-run flag for install/uninstall actions
    dry-run: # optional
    # The path of the chart.
    chart-path: # optional, default is helm/
    # The repository of the chart.
    chart-repository: # optional
    # The chart version
    version: # optional
    # Timeout for the job.
    timeout: # default is 0s
    # Update chart dependencies
    update-deps: # optional, default is true
    # Comma separated list of helm plugins to install. e.x: https://github.com/hypnoglow/helm-s3.git,https://github.com/someuser/helm-plugin.git
    plugins: # optional
    # Add the --wait flag to helm
    helm-wait: # optional
    # Add the --atomic flag to rollback on failure
    atomic: # optional
    # Verify certificates of HTTPS-enabled servers using this CA bundle.
    ca-file: # optional
    # Identify HTTPS client using this SSL certificate file.
    cert-file: # optional
    # Identify HTTPS client using this SSL key file.
    key-file: # optional
    # Skip tls certificate checks for the chart download.
    insecure-skip-tls-verify: # optional
    # Pass credentials to all domains.
    pass-credentials: # optional
    # Chart repository password where to locate the requested chart.
    password: # optional
    # Chart repository username where to locate the requested chart.
    username: # optional
    # Uses the secrets with vals backend to apply the chart
    use-secrets-vals: # optional
    # Append any string containing any extra option that might escape the ones present in this action.
    helm-extra-args: # optional
          
